version: "3"

services:
    proxy:
        image: traefik   # the official Traefik docker image
        container_name: traefik
        restart: on-failure
        command: --api --docker # enables the web UI and tells Traefik to listen to docker
        ports:
            - 80:80     # the HTTP port
            - 443:443   # https Port
            - 8080:8080 # the Web UI (enabled by --api)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./proxy/traefik.toml:/etc/traefik/traefik.toml
            - ./proxy/acme.json:/acme.json
            - ./proxy:/opt/traefik/

    turing-api:
        build: turing-api/
        image: turing-api
        container_name: turing-api
        volumes:
            - ./turing-api:/backend
        environment:
            - DATABASE_URL=mysql://turing:turing@localhost/turing
            - STRIPE_PUBLISHABLE_KEY=somekey
            - STRIPE_SECRET_KEY=sk_test_lomdOfxbm7QDgZWvR82UhV6D
            - SENDGRID_API_KEY=somekey
            - JWT_KEY=23456780poiuytrewq
        links:
            - db-test
            - proxy:local.turing.com
        labels:
            - traefik.enable=true
            - traefik.port=5000
            - traefik.api.backend=turing-api
            - traefik.api.frontend.passHostHeader=true
            - traefik.api.frontend.rule=Host:local.turing.com;PathPrefix:/api
        depends_on:
            - db-test
        command: bash -c "npm install && bash ./turing-entrypoint.sh"

    turing-shop:
        build: turing-shop/
        image: turing-shop
        container_name: turing-shop
        volumes:
            - ./turing-shop:/usr/src/app/
        links:
            - turing-api
        environment:
            - ENV=local
        labels:
            - traefik.enable=true
            - traefik.port=4200
            - traefik.frontend.passHostHeader=true
            - traefik.app.backend=turing-shop
            - traefik.app.frontend.rule=Host:local.turing.com;PathPrefix:/dashboard
            - traefik.dashboard.backend=turing-shop
            - traefik.dashboard.frontend.rule=Host:local.turing.com;Path:/
            - traefik.dashboard.frontend.redirect.regex=^http://local.turing.com/(.*)
            - traefik.dashboard.frontend.redirect.replacement=http://local.turing.com/dashboard/$$1
        command: bash -c "npm install && bash ./docker/run.sh"

    db-test:
        image: mysql:5.7
        container_name: db-test
        command: ["--general_log=1", "--log_output=TABLE", "--explicit_defaults_for_timestamp=1"]
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=turing
            - MYSQL_DATABASE=turing_test
            - MYSQL_USER=turing
        ports:
            - 3306:3306
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
            interval: 30s
            timeout: 30s
            retries: 10
